// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/user.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	protos/user.proto

It has these top-level messages:
	UserSql
	Script
	ObjScript
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type UserSql struct {
	User   string     `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
	Script string     `protobuf:"bytes,2,opt,name=script" json:"script,omitempty"`
	Obj    *ObjScript `protobuf:"bytes,3,opt,name=obj" json:"obj,omitempty"`
}

func (m *UserSql) Reset()                    { *m = UserSql{} }
func (m *UserSql) String() string            { return proto1.CompactTextString(m) }
func (*UserSql) ProtoMessage()               {}
func (*UserSql) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *UserSql) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *UserSql) GetScript() string {
	if m != nil {
		return m.Script
	}
	return ""
}

func (m *UserSql) GetObj() *ObjScript {
	if m != nil {
		return m.Obj
	}
	return nil
}

type Script struct {
	Script string `protobuf:"bytes,1,opt,name=script" json:"script,omitempty"`
}

func (m *Script) Reset()                    { *m = Script{} }
func (m *Script) String() string            { return proto1.CompactTextString(m) }
func (*Script) ProtoMessage()               {}
func (*Script) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Script) GetScript() string {
	if m != nil {
		return m.Script
	}
	return ""
}

type ObjScript struct {
	TableColumns []string `protobuf:"bytes,1,rep,name=tableColumns" json:"tableColumns,omitempty"`
}

func (m *ObjScript) Reset()                    { *m = ObjScript{} }
func (m *ObjScript) String() string            { return proto1.CompactTextString(m) }
func (*ObjScript) ProtoMessage()               {}
func (*ObjScript) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ObjScript) GetTableColumns() []string {
	if m != nil {
		return m.TableColumns
	}
	return nil
}

func init() {
	proto1.RegisterType((*UserSql)(nil), "proto.UserSql")
	proto1.RegisterType((*Script)(nil), "proto.Script")
	proto1.RegisterType((*ObjScript)(nil), "proto.ObjScript")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for AOBService service

type AOBServiceClient interface {
	ParseAndCheckAccess(ctx context.Context, in *UserSql, opts ...grpc.CallOption) (*UserSql, error)
}

type aOBServiceClient struct {
	cc *grpc.ClientConn
}

func NewAOBServiceClient(cc *grpc.ClientConn) AOBServiceClient {
	return &aOBServiceClient{cc}
}

func (c *aOBServiceClient) ParseAndCheckAccess(ctx context.Context, in *UserSql, opts ...grpc.CallOption) (*UserSql, error) {
	out := new(UserSql)
	err := grpc.Invoke(ctx, "/proto.AOBService/ParseAndCheckAccess", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for AOBService service

type AOBServiceServer interface {
	ParseAndCheckAccess(context.Context, *UserSql) (*UserSql, error)
}

func RegisterAOBServiceServer(s *grpc.Server, srv AOBServiceServer) {
	s.RegisterService(&_AOBService_serviceDesc, srv)
}

func _AOBService_ParseAndCheckAccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserSql)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AOBServiceServer).ParseAndCheckAccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.AOBService/ParseAndCheckAccess",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AOBServiceServer).ParseAndCheckAccess(ctx, req.(*UserSql))
	}
	return interceptor(ctx, in, info, handler)
}

var _AOBService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.AOBService",
	HandlerType: (*AOBServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ParseAndCheckAccess",
			Handler:    _AOBService_ParseAndCheckAccess_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/user.proto",
}

func init() { proto1.RegisterFile("protos/user.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 206 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x8f, 0xcf, 0x4b, 0x85, 0x40,
	0x10, 0xc7, 0xdb, 0x2c, 0xc3, 0x29, 0xa2, 0x26, 0x88, 0xa5, 0xd3, 0xb2, 0x27, 0x4f, 0xef, 0xc1,
	0xeb, 0xd0, 0xd9, 0xa4, 0xb3, 0xa1, 0x74, 0xe8, 0xe8, 0x6e, 0x03, 0x69, 0xe6, 0xda, 0x8e, 0xf6,
	0xf7, 0x87, 0xab, 0x84, 0x75, 0x9a, 0xef, 0x0f, 0xe6, 0xc3, 0x0c, 0x5c, 0x0f, 0xde, 0x8d, 0x8e,
	0xf7, 0x13, 0x93, 0xdf, 0x05, 0x8d, 0xa7, 0x61, 0xe8, 0x57, 0x38, 0x7b, 0x61, 0xf2, 0xd5, 0x57,
	0x87, 0x08, 0x27, 0x73, 0x2f, 0x85, 0x12, 0x69, 0x52, 0x06, 0x8d, 0xb7, 0x10, 0xb3, 0xf5, 0xcd,
	0x30, 0xca, 0xe3, 0x90, 0xae, 0x0e, 0x35, 0x44, 0xce, 0xb4, 0x32, 0x52, 0x22, 0x3d, 0x3f, 0x5c,
	0x2d, 0xc8, 0x5d, 0x61, 0xda, 0x2a, 0xd4, 0xe5, 0x5c, 0x6a, 0x05, 0xf1, 0x62, 0x37, 0x14, 0xb1,
	0xa5, 0xe8, 0x3d, 0x24, 0xbf, 0x3b, 0xa8, 0xe1, 0x62, 0xac, 0x4d, 0x47, 0xb9, 0xeb, 0xa6, 0xcf,
	0x9e, 0xa5, 0x50, 0x51, 0x9a, 0x94, 0x7f, 0xb2, 0xc3, 0x13, 0x40, 0x56, 0x3c, 0x56, 0xe4, 0xbf,
	0x1b, 0x4b, 0xf8, 0x00, 0x37, 0xcf, 0xb5, 0x67, 0xca, 0xfa, 0xb7, 0xfc, 0x9d, 0xec, 0x47, 0x66,
	0x2d, 0x31, 0xe3, 0xe5, 0x7a, 0xce, 0xfa, 0xd7, 0xdd, 0x3f, 0xaf, 0x8f, 0x4c, 0x1c, 0x82, 0xfb,
	0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x3c, 0x09, 0x8d, 0x7a, 0x17, 0x01, 0x00, 0x00,
}
