// Code generated by protoc-gen-go.
// source: user_script.proto
// DO NOT EDIT!

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	user_script.proto

It has these top-level messages:
	Script
	ObjScript
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type Script struct {
	Script string `protobuf:"bytes,1,opt,name=script" json:"script,omitempty"`
}

func (m *Script) Reset()                    { *m = Script{} }
func (m *Script) String() string            { return proto1.CompactTextString(m) }
func (*Script) ProtoMessage()               {}
func (*Script) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Script) GetScript() string {
	if m != nil {
		return m.Script
	}
	return ""
}

type ObjScript struct {
	ObjScript string `protobuf:"bytes,1,opt,name=objScript" json:"objScript,omitempty"`
}

func (m *ObjScript) Reset()                    { *m = ObjScript{} }
func (m *ObjScript) String() string            { return proto1.CompactTextString(m) }
func (*ObjScript) ProtoMessage()               {}
func (*ObjScript) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ObjScript) GetObjScript() string {
	if m != nil {
		return m.ObjScript
	}
	return ""
}

func init() {
	proto1.RegisterType((*Script)(nil), "proto.Script")
	proto1.RegisterType((*ObjScript)(nil), "proto.ObjScript")
}

func init() { proto1.RegisterFile("user_script.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 133 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x12, 0x2c, 0x2d, 0x4e, 0x2d,
	0x8a, 0x2f, 0x4e, 0x2e, 0xca, 0x2c, 0x28, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05,
	0x53, 0x4a, 0x0a, 0x5c, 0x6c, 0xc1, 0x60, 0x61, 0x21, 0x31, 0x2e, 0x36, 0x88, 0x02, 0x09, 0x46,
	0x05, 0x46, 0x0d, 0xce, 0x20, 0x28, 0x4f, 0x49, 0x93, 0x8b, 0xd3, 0x3f, 0x29, 0x0b, 0xaa, 0x48,
	0x86, 0x8b, 0x33, 0x1f, 0xc6, 0x81, 0xaa, 0x43, 0x08, 0x18, 0x59, 0x73, 0x71, 0x39, 0xfa, 0x3b,
	0x05, 0xa7, 0x16, 0x95, 0x65, 0x26, 0xa7, 0x0a, 0xe9, 0x72, 0x71, 0x04, 0x24, 0x16, 0x15, 0xa7,
	0x06, 0x17, 0xe6, 0x08, 0xf1, 0x42, 0x6c, 0xd5, 0x83, 0x28, 0x94, 0x12, 0x80, 0x72, 0xe1, 0x06,
	0x2b, 0x31, 0x24, 0xb1, 0x81, 0x85, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0xfa, 0xd3, 0x3f,
	0x31, 0xac, 0x00, 0x00, 0x00,
}
